openapi: 3.1.0
info:
  title: Orbtronics L1 Mechatronics Engineer Backend
  description: Backend for IoT device information
  version: 0.1.0
tags:
  - name: device
    description: device operations
servers:
  - url: http://localhost:8000/api
    description: Development environment
paths:
  /user/device:
    get:
      operationId: getDeviceInformation
      description: get current device information stored in memory
      tags:
        - device
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: application/json
      responses:
        "200":
          description: device information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceData"
    post:
      operationId: postDeviceInformation
      description: store or update device information in memory
      tags:
        - device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceData"
      responses:
        "201":
          description: device information stored successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceData"
components:
  schemas:
    DeviceData:
      type: object
      properties:
        deviceName:
          type: string
          example: device01
        temperature:
          type: number
          format: float
          example: 55.5
        humidity:
          type: number
          format: float
          example: 45.5
      required:
        - deviceName
        - temperature
        - humidity
