services:
  backend:
    restart: always
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}

  simulation:
    restart: always
