services:
  backend:
    restart: always
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_CONNECTION_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}?sslmode=disable

  simulation:
    restart: always
    build:
      context: ./src/simulation
      dockerfile: Dockerfile
    environment:
      SERVER_URL: http://backend:${SERVER_PORT}/api/user/device
