services:
  frontend:
    restart: always
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      VITE_SERVER_URL: http://localhost:${SERVER_PORT}/api/user/device
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_CONNECTION_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}?sslmode=disable
      FRONTEND_URL: http://localhost:4173
    depends_on:
      - database

  simulation:
    restart: always
    build:
      context: ./src/simulation
      dockerfile: Dockerfile
    environment:
      SERVER_URL: http://backend:${SERVER_PORT}/api/user/device
    depends_on:
      - backend

  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
