# https://github.com/numtide/treefmt-nix/tree/main/examples

[formatter.black]
command = "black"
excludes = []
includes = ["*.py", "*.pyi"]
options = []

[formatter.isort]
command = "isort"
excludes = []
includes = ["*.py", "*.pyi"]
options = []

[formatter.gofmt]
command = "gofmt"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.nixfmt]
command = "nixfmt"
options = []
includes = ["*.nix"]
excludes = []
priority = 0

[formatter.prettier]
command = "prettier"
excludes = []
includes = [
  "*.cjs",
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.json5",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.mjs",
  "*.scss",
  "*.ts",
  "*.tsx",
  "*.vue",
  "*.yaml",
  "*.yml",
]
options = ["--write"]